### ISSUE TITLE
Enable froide model translation

### ISSUE THREAD

**Issue by milkcask** [ODHK/opengov.hk#19]
Some froide models should provide translated contents.
- PublicBody
  - name
  - description
  - url
  - classification
  - request_note
- FoiRequest
  - title

**Comment by tijptjik** [comment]
Could you elaborate a bit about this one please? :)

**Comment by milkcask** [comment]
@tijptjik edited.

I would probably go for django-modeltranslation (https://django-modeltranslation.readthedocs.org/en/latest/)
