### ISSUE TITLE
Review and verify the public bodies list

### ISSUE THREAD

**Issue by tijptjik** [ODHK/opengov.hk#5]
[Public Bodies Source](https://docs.google.com/a/type.hk/spreadsheets/d/1x3WISjwPeC81n3GQTsqPxvKLnxpNehqyaWjdyCTX1bA/edit?usp=sharing)

**Comment by zaclz** [comment]
Checked 'f' 1-40, against the www.access.gov.hk database and the Government Telephone Directory; amended where necessary.

Two departments in particular need to be checked later: the contact person indicated on www.access.gov.hk no longer work in the department when checked against Government Directory data.

These are f=21 (Home Affairs Department Wan Chai), and f=22 (HAD Eastern). The rows are highlighted in yellow.

**Comment by tijptjik** [comment]
Thanks a lot @zaclz! Do you think you'll have time over the weekend to go through all of them? 

I've ported the spreadsheet over to Google's new Spreadsheets format so we get better revision control and functions. 

It's now hosted at [Public Bodies Source](https://docs.google.com/a/type.hk/spreadsheets/d/1x3WISjwPeC81n3GQTsqPxvKLnxpNehqyaWjdyCTX1bA/edit?usp=sharing)

**Comment by zaclz** [comment]
I have an hour or two on this - might not cover all, but will keep posted on this space.

**Comment by gfrmin** [comment]
Mart, is the location for the spreadsheet available anywhere else except this ticket? Like in the main README?

**Comment by tijptjik** [comment]
Thanks Calvin!

@Guy, feel free to add it to the readme.md and add some documentation about
our organisation as well.

**Comment by gfrmin** [comment]
Will do :)

**Comment by zaclz** [comment]
f41-100 checked now.

**Comment by zaclz** [comment]
All checked now. Rows highlighted in yellow either contain incomplete (or inconsistent) information so I've highlighted them for further checks later; not much can be done at this stage. Otherwise the list is most up to date now.
